version: "3"

services:
  duoc-plus:
    image:
    container_name: duoc-plus
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs:/etc/nginx/conf.d
    restart: unless-stopped
