// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://www.duoc.cl/politica-privacidad/",
        "contact": {
            "name": "Matias \"Hinotori\" Canovas",
            "url": "https://github.com/imhinotori/",
            "email": "hello@hinotori.moe"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/license/mit/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attendance": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user attendance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved attendance",
                        "schema": {
                            "$ref": "#/definitions/common.Attendance"
                        }
                    },
                    "400": {
                        "description": "Error getting attendance.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Authenticate",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of the user",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password of the user",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/common.AuthenticationResponse"
                        }
                    },
                    "400": {
                        "description": "Error reading body.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Refresh token",
                        "name": "refresh_token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/common.AuthenticationResponse"
                        }
                    },
                    "400": {
                        "description": "Error reading body.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/grades": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user grades",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved grades",
                        "schema": {
                            "$ref": "#/definitions/common.Grades"
                        }
                    },
                    "400": {
                        "description": "Error getting grades.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/schedule": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get user schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved schedule",
                        "schema": {
                            "$ref": "#/definitions/common.CareerSchedule"
                        }
                    },
                    "400": {
                        "description": "Error getting schedule.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Attendance": {
            "type": "object",
            "properties": {
                "attendance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.SubjectAttendance"
                    }
                },
                "degree_code": {
                    "type": "string"
                },
                "degree_name": {
                    "type": "string"
                }
            }
        },
        "common.AttendanceDetail": {
            "type": "object",
            "properties": {
                "attendance": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "common.AuthenticationResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "access_token_expires_in": {
                    "type": "integer"
                },
                "refresh_expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "common.CareerSchedule": {
            "type": "object",
            "properties": {
                "career_name": {
                    "type": "string"
                },
                "schedule": {
                    "$ref": "#/definitions/common.Week"
                }
            }
        },
        "common.Course": {
            "type": "object",
            "properties": {
                "classroom": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "instructor": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "subject_code": {
                    "type": "string"
                },
                "subject_name": {
                    "type": "string"
                }
            }
        },
        "common.Grades": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Subject"
                    }
                }
            }
        },
        "common.Subject": {
            "type": "object",
            "properties": {
                "average": {
                    "type": "number"
                },
                "code": {
                    "type": "string"
                },
                "exams": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "name": {
                    "type": "string"
                },
                "partials": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "common.SubjectAttendance": {
            "type": "object",
            "properties": {
                "assisted_classes": {
                    "type": "integer"
                },
                "classes_held": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.AttendanceDetail"
                    }
                },
                "name": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                }
            }
        },
        "common.Week": {
            "type": "object",
            "properties": {
                "friday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Course"
                    }
                },
                "monday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Course"
                    }
                },
                "saturday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Course"
                    }
                },
                "sunday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Course"
                    }
                },
                "thursday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Course"
                    }
                },
                "tuesday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Course"
                    }
                },
                "wednesday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Course"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api-duoc.hinotori.moe",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Duoc Plus API",
	Description:      "Duoc Plus, is a REST API that allows you to access your grades, schedule and attendance from DuocUC.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
